apiVersion: v2
type: application
name: vault-operator
version: 1.20.0-dev.2
appVersion: 1.19.0
description: Kubernetes operator for Hashicorp Vault
icon: https://raw.githubusercontent.com/banzaicloud/bank-vaults/main/docs/images/logo/bank-vaults-logo.svg
keywords:
  - vault
  - hashicorp
  - secret
  - operator
home: https://bank-vaults.dev
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/bank-vaults/vault-operator
maintainers:
  - name: Bank Vaults Maintainers
    email: team@bank-vaults.dev
